[custom]

;规则集定义
ruleset=💎 VPS-IP1,https://raw.githubusercontent.com/silver9127/ruanluyou/refs/heads/main/HOTKME2.list
ruleset=💎 VPS-IP2,https://raw.githubusercontent.com/silver9127/ruanluyou/refs/heads/main/HOTKME3.list
ruleset=💻 搬瓦工,https://raw.githubusercontent.com/silver9127/ruanluyou/refs/heads/main/HOTKME1.list



;策略组定义
custom_proxy_group=💻 搬瓦工`select`(?=.*(vless-reality|tuic-443))^((?!(vless-reality 2|tuic-443 2|vless-reality 3|tuic-443 3)).)*$
custom_proxy_group=💎 VPS-IP1`select`(vless-reality 2|tuic-443 2)
custom_proxy_group=💎 VPS-IP2`select`(vless-reality 3|tuic-443 3)

;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true
